macro(have_framework_target unistream_root_path)
  if(TARGET unistream_core)
    set(HAVE_FRAMEWORK_TARGET TRUE)
  else()
    if(NOT EXISTS ${unistream_root_path}/lib/libunistream_core.so)
      message(FATAL_ERROR "Build framework first")
    endif()
    link_directories(${unistream_root_path}/lib)
  endif()
  include_directories(${unistream_root_path}/framework/include)
endmacro()

macro(have_easydk_target unistream_root_path)
  if(TARGET easydk)
    set(HAVE_EASYDK_TARGET TRUE)
  else()
    if(NOT EXISTS ${unistream_root_path}/easydk/lib/libeasydk.so)
      message(FATAL_ERROR "Build easydk first")
    endif()
    link_directories(${unistream_root_path}/easydk/lib)
  endif()
  include_directories(${unistream_root_path}/easydk/include)
  include_directories(${unistream_root_path}/easydk/include/infer_server)
  include_directories(${AXCL_INCLUDE_DIR})
endmacro()

macro(have_modules_target unistream_root_path)
  if(TARGET unistream_va)
    set(HAVE_MODULES_TARGET TRUE)
  else()
    if(NOT EXISTS ${unistream_root_path}/lib/libunistream_va.so)
      message(FATAL_ERROR "Build modules first")
    endif()
    link_directories(${unistream_root_path}/lib)
  endif()
endmacro()

macro(have_modules_contrib_target unistream_root_path)
  if(TARGET unistream_contrib)
    set(HAVE_MODULES_CONTRIB_TARGET TRUE)
    set(HAVE_MODULES_CONTRIB TRUE)
  else()
    if(EXISTS ${unistream_root_path}/lib/libunistream_contrib.so)
      set(HAVE_MODULES_CONTRIB TRUE)
      link_directories(${unistream_root_path}/lib)
    endif()
  endif()
endmacro()
